'use client'

import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { Atom, Check, Loader2, Copy as CopyIcon, Radar, Trophy, ImageIcon, Film, Users, ChevronRight } from 'lucide-react'
import { Panel, PanelHeader, Pill } from '@/components/reactor/ui'
import { FaceLibrary } from '@/components/reactor/FaceLibrary'
import { ReactorModal } from '@/components/campaign-reactor/ReactorModal'
import { reactorOutputTypes } from '@/lib/reactor-data'
import type { ReactorInputs } from '@/lib/reactor-inputs'
import { recommendVideoModel } from '@/lib/video/recommend'
import type { ModelAvailability } from '@/lib/video/types'
import { recommendImageModel } from '@/lib/image/recommend'
import type { ImageModelAvailability } from '@/lib/image/types'

interface Concept {
  type: string
  text: string
  basis?: string
  learningCheck?: string
  score?: number
  imageUrl?: string
}

interface TelemetryLine {
  text: string
  kind: 'step' | 'retrieval' | 'specialist'
}

type VideoUiState = { status: 'rendering' | 'done' | 'error'; url?: string; message?: string }

// Normalize an output/concept type so agent-generated media keyed by type lines
// up with the concept the agent submits ("Static Concepts" ≈ "Static Concept").
const normType = (s: string) => s.toLowerCase().replace(/s$/, '').trim()

export function Workbench() {
  const [modalOpen, setModalOpen] = useState(false)
  const [showRefs, setShowRefs] = useState(false)
  // The angle from the last fired run — used when logging a winner outcome.
  const [lastAngle, setLastAngle] = useState('')
  const [phase, setPhase] = useState<'idle' | 'firing' | 'done'>('idle')
  const [concepts, setConcepts] = useState<Concept[]>([])
  const [telemetry, setTelemetry] = useState<TelemetryLine[]>([])
  const [error, setError] = useState<string | null>(null)
  const [copied, setCopied] = useState<string | null>(null)
  const [logged, setLogged] = useState<Set<string>>(new Set())
  const [creatives, setCreatives] = useState<
    Record<string, { status: 'working' | 'done' | 'error'; url?: string; message?: string }>
  >({})
  // Higgsfield media generated by the agent during the run, keyed by concept type.
  const [agentMedia, setAgentMedia] = useState<Record<string, { image?: string; video?: VideoUiState }>>({})
  // Manually triggered "Animate" renders, keyed by concept text.
  const [manualVideos, setManualVideos] = useState<Record<string, VideoUiState>>({})
  // Available models (from the API). Selection is now agent-decided — the modal
  // no longer exposes pickers — so we resolve each manual card action to the
  // recommended model for the concepts on screen.
  const [videoModels, setVideoModels] = useState<ModelAvailability[]>([])
  const [imageModels, setImageModels] = useState<ImageModelAvailability[]>([])
  // Face library: reference image URLs that lock a consistent face across UGC
  // clips (Seedance 2.0 reference-to-video). One URL per line or comma-separated.
  // Selected reference assets from the Face Library (saved roster) → power
  // Seedance 2.0 reference-to-video for consistent-character in-house UGC.
  const [faceUrls, setFaceUrls] = useState<string[]>([])
  const [refVideos, setRefVideos] = useState<string[]>([])
  const hasRefs = faceUrls.length > 0 || refVideos.length > 0
  const handleFaceSelection = useCallback((images: string[], videos: string[]) => {
    setFaceUrls(images.slice(0, 9))
    setRefVideos(videos.slice(0, 3))
  }, [])
  const feedRef = useRef<HTMLDivElement>(null)

  // Load the model menus once so the user can pick (and we can recommend).
  useEffect(() => {
    fetch('/api/video/models')
      .then((r) => r.json())
      .then((d) => {
        if (Array.isArray(d.models)) setVideoModels(d.models as ModelAvailability[])
      })
      .catch(() => {})
    fetch('/api/image/models')
      .then((r) => r.json())
      .then((d) => {
        if (Array.isArray(d.models)) setImageModels(d.models as ImageModelAvailability[])
      })
      .catch(() => {})
  }, [])

  // Dashboard's "New Creative Campaign" CTA links here with ?modal=open — open
  // the modal on arrival, then strip the param so a refresh doesn't reopen it.
  useEffect(() => {
    if (typeof window === 'undefined') return
    const params = new URLSearchParams(window.location.search)
    if (params.get('modal') === 'open') {
      setModalOpen(true)
      params.delete('modal')
      const qs = params.toString()
      window.history.replaceState(null, '', window.location.pathname + (qs ? `?${qs}` : ''))
    }
  }, [])

  // Recommend a model from whatever concepts are on screen (or the full output
  // menu before a run) so the per-card Generate / Animate / UGC actions resolve
  // to a sensible default without a picker.
  const activeOutputs = useMemo(
    () => (concepts.length ? concepts.map((c) => c.type) : reactorOutputTypes),
    [concepts],
  )
  const recommendation = useMemo(
    () => (videoModels.length ? recommendVideoModel(activeOutputs, videoModels) : null),
    [activeOutputs, videoModels],
  )
  const resolvedVideoModel = recommendation?.modelId
  const imageRecommendation = useMemo(
    () => (imageModels.length ? recommendImageModel(activeOutputs, imageModels) : null),
    [activeOutputs, imageModels],
  )
  const resolvedImageModel = imageRecommendation?.modelId

  const pushTelemetry = (line: TelemetryLine) => {
    setTelemetry((prev) => [...prev, line])
    requestAnimationFrame(() => feedRef.current?.scrollTo({ top: 1e9, behavior: 'smooth' }))
  }

  // Poll a video render until it completes or fails (model-aware across providers).
  const pollVideo = async (
    requestId: string,
    model: string | undefined,
    onUpdate: (s: VideoUiState) => void,
    responseUrl?: string,
  ) => {
    const modelQuery = model ? `&model=${encodeURIComponent(model)}` : ''
    const responseQuery = responseUrl ? `&responseUrl=${encodeURIComponent(responseUrl)}` : ''
    for (let i = 0; i < 90; i++) {
      await new Promise((r) => setTimeout(r, 4000))
      try {
        const res = await fetch(
          `/api/generate-video?requestId=${encodeURIComponent(requestId)}${modelQuery}${responseQuery}`,
        ).then((r) => r.json())
        if (res.status === 'completed' && res.videoUrl) {
          onUpdate({ status: 'done', url: res.videoUrl })
          return
        }
        if (res.status === 'failed' || res.status === 'nsfw') {
          onUpdate({ status: 'error' })
          return
        }
      } catch {
        /* transient — keep polling */
      }
    }
    onUpdate({ status: 'error' })
  }

  const fire = async (inputs: ReactorInputs) => {
    setPhase('firing')
    setConcepts([])
    setTelemetry([])
    setError(null)
    setAgentMedia({})
    setManualVideos({})

    const angle = inputs.angleIsAgentDecided ? 'Agent decides' : inputs.angle
    setLastAngle(angle)
    // When the agent decides outputs we pass the full menu as the allowed set;
    // the system prompt instructs it to pick the best subset for this brief.
    const outputs = inputs.outputTypesAgentDecided ? reactorOutputTypes : inputs.outputTypes

    try {
      const res = await fetch('/api/campaign-reactor', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          angle,
          outputs,
          reactorInputs: inputs,
        }),
      })
      if (!res.body) throw new Error('No response stream')

      const reader = res.body.getReader()
      const decoder = new TextDecoder()
      let buffer = ''

      // Parse the SSE stream line by line.
      for (;;) {
        const { done, value } = await reader.read()
        if (done) break
        buffer += decoder.decode(value, { stream: true })
        const parts = buffer.split('\n\n')
        buffer = parts.pop() ?? ''
        for (const part of parts) {
          const line = part.replace(/^data: /, '').trim()
          if (!line) continue
          let ev: { type: string; [k: string]: unknown }
          try {
            ev = JSON.parse(line)
          } catch {
            continue
          }
          if (ev.type === 'step') pushTelemetry({ text: ev.text as string, kind: 'step' })
          else if (ev.type === 'retrieval')
            pushTelemetry({ text: `${ev.system} · ${ev.title}`, kind: 'retrieval' })
          else if (ev.type === 'delegate')
            pushTelemetry({
              text:
                ev.status === 'start'
                  ? `${ev.specialist} — analyzing…`
                  : `${ev.specialist} — ${ev.summary}`,
              kind: 'specialist',
            })
          else if (ev.type === 'media') {
            const key = normType((ev.conceptType as string) || '')
            if (ev.mediaType === 'image') {
              setAgentMedia((p) => ({ ...p, [key]: { ...p[key], image: ev.url as string } }))
            } else if (ev.mediaType === 'video') {
              setAgentMedia((p) => ({ ...p, [key]: { ...p[key], video: { status: 'rendering' } } }))
              const requestId = ev.requestId as string | undefined
              if (requestId) {
                pollVideo(
                  requestId,
                  ev.model as string | undefined,
                  (s) => setAgentMedia((p) => ({ ...p, [key]: { ...p[key], video: s } })),
                  ev.responseUrl as string | undefined,
                )
              }
            }
          } else if (ev.type === 'concept') setConcepts((p) => [...p, ev.concept as Concept])
          else if (ev.type === 'error') setError(ev.message as string)
          else if (ev.type === 'done') setPhase('done')
        }
      }
      setPhase('done')
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Reactor failed')
      setPhase('done')
    }
  }

  const copy = (text: string) => {
    navigator.clipboard?.writeText(text)
    setCopied(text)
    setTimeout(() => setCopied(null), 1500)
  }

  // A concept whose brief is a moving creative (Video / Testimonial) renders a
  // video ad; everything else renders a still. Either way we feed the agent's
  // exact design brief (c.text) as the generation prompt.
  const isVideoConcept = (c: Concept) => /video|testimonial/i.test(c.type)

  // Turn a concept's design brief into the right creative — image or video.
  const generateCreative = async (c: Concept) => {
    if (isVideoConcept(c)) return generateVideoCreative(c)

    setCreatives((p) => ({ ...p, [c.text]: { status: 'working' } }))
    try {
      const res = await fetch('/api/generate-image', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          prompt: `${c.text}\n\nRender as a premium Meta ad creative for The Professional Builder — photographic, on-site builder context, high contrast, leave room for text overlay.`,
          aspectRatio: '1:1',
          model: resolvedImageModel,
        }),
      }).then((r) => r.json())

      if (res.success && res.imageUrl) {
        setCreatives((p) => ({ ...p, [c.text]: { status: 'done', url: res.imageUrl } }))
      } else {
        setCreatives((p) => ({
          ...p,
          [c.text]: {
            status: 'error',
            message:
              res.error ||
              (res.demo
                ? 'No image API key set — add FAL_KEY, GEMINI_API_KEY, OPENAI_API_KEY, or HF_CREDENTIALS'
                : 'Generation failed'),
          },
        }))
      }
    } catch {
      setCreatives((p) => ({ ...p, [c.text]: { status: 'error', message: 'Generation failed' } }))
    }
  }

  // Render a video ad straight from the concept's brief (text-to-video) using
  // the selected/recommended model.
  const generateVideoCreative = async (c: Concept) => {
    setManualVideos((p) => ({ ...p, [c.text]: { status: 'rendering' } }))
    try {
      const res = await fetch('/api/generate-video', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          prompt: c.text,
          mode: 'text-to-video',
          model: resolvedVideoModel,
          aspectRatio: '9:16',
        }),
      }).then((r) => r.json())

      if (res.success && res.requestId) {
        pollVideo(
          res.requestId,
          res.modelId,
          (s) => setManualVideos((p) => ({ ...p, [c.text]: s })),
          res.responseUrl,
        )
      } else {
        setManualVideos((p) => ({
          ...p,
          [c.text]: {
            status: 'error',
            message:
              res.error ||
              (res.demo ? 'No video API key set — add FAL_KEY or HF_CREDENTIALS' : 'Video render failed'),
          },
        }))
      }
    } catch {
      setManualVideos((p) => ({ ...p, [c.text]: { status: 'error', message: 'Video render failed' } }))
    }
  }

  // Animate an existing still into a video with Higgsfield (image -> video).
  const animate = async (c: Concept, imageUrl: string) => {
    setManualVideos((p) => ({ ...p, [c.text]: { status: 'rendering' } }))
    try {
      const res = await fetch('/api/generate-video', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          imageUrl,
          mode: 'image-to-video',
          model: resolvedVideoModel,
          prompt: `Cinematic motion for a builder ad: ${c.text}`,
        }),
      }).then((r) => r.json())

      if (res.success && res.requestId) {
        pollVideo(
          res.requestId,
          res.modelId,
          (s) => setManualVideos((p) => ({ ...p, [c.text]: s })),
          res.responseUrl,
        )
      } else {
        setManualVideos((p) => ({
          ...p,
          [c.text]: {
            status: 'error',
            message:
              res.error ||
              (res.demo ? 'No video API key set — add FAL_KEY or HF_CREDENTIALS' : 'Video render failed'),
          },
        }))
      }
    } catch {
      setManualVideos((p) => ({ ...p, [c.text]: { status: 'error', message: 'Video render failed' } }))
    }
  }

  // Generate UGC with a consistent face — Seedance 2.0 reference-to-video using
  // the face library (reference images) + the concept's brief. Forces Seedance
  // since it's the model that supports reference-to-video.
  const generateUGC = async (c: Concept) => {
    if (!hasRefs) return
    setManualVideos((p) => ({ ...p, [c.text]: { status: 'rendering' } }))
    try {
      const res = await fetch('/api/generate-video', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          prompt: c.text,
          mode: 'reference-to-video',
          model: 'seedance-2.0',
          imageUrls: faceUrls,
          videoUrls: refVideos,
          aspectRatio: '9:16',
        }),
      }).then((r) => r.json())

      if (res.success && res.requestId) {
        pollVideo(
          res.requestId,
          res.modelId,
          (s) => setManualVideos((p) => ({ ...p, [c.text]: s })),
          res.responseUrl,
        )
      } else {
        setManualVideos((p) => ({
          ...p,
          [c.text]: {
            status: 'error',
            message:
              res.error ||
              (res.demo ? 'No video API key set — add FAL_KEY' : 'UGC render failed'),
          },
        }))
      }
    } catch {
      setManualVideos((p) => ({ ...p, [c.text]: { status: 'error', message: 'UGC render failed' } }))
    }
  }

  // Log a winner — feeds it back into the knowledge layer as a new pattern.
  const markWinner = async (c: Concept) => {
    setLogged((prev) => new Set(prev).add(c.text))
    try {
      await fetch('/api/campaign-reactor/outcome', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ angle: lastAngle, concept: c, verdict: 'winner' }),
      })
    } catch {
      /* best-effort logging */
    }
  }

  const imageFor = (c: Concept) =>
    c.imageUrl || agentMedia[normType(c.type)]?.image || creatives[c.text]?.url
  const videoFor = (c: Concept): VideoUiState | undefined =>
    manualVideos[c.text] || agentMedia[normType(c.type)]?.video

  return (
    <div className="space-y-6">
      {/* Trigger bar — opens the multi-step campaign modal */}
      <div className="flex flex-wrap items-center justify-between gap-4">
        <div>
          <h2 className="font-display text-lg font-semibold text-white">Configure your campaign</h2>
          <p className="mt-0.5 text-sm text-white/45">
            Set the brief, audience, and offer across four quick steps — then fire the reactor.
          </p>
        </div>
        <button
          type="button"
          onClick={() => setModalOpen(true)}
          disabled={phase === 'firing'}
          className="fire-btn inline-flex items-center gap-2 rounded-full px-6 py-3.5 font-display text-base font-bold uppercase tracking-wide text-white"
        >
          {phase === 'firing' ? (
            <>
              <Loader2 size={16} className="animate-spin" /> Firing Reactor…
            </>
          ) : (
            <>
              <Atom size={16} /> New Creative Campaign
            </>
          )}
        </button>
      </div>

      {/* Reference library (optional) — powers consistent-face UGC on video concepts */}
      <Panel className="p-4">
        <button
          type="button"
          onClick={() => setShowRefs((v) => !v)}
          className="flex w-full items-center gap-2 text-[11px] font-medium uppercase tracking-[0.08em] text-white/45 transition-colors hover:text-white/70"
        >
          <ChevronRight size={13} className={`transition-transform ${showRefs ? 'rotate-90' : ''}`} />
          <Users size={13} />
          Reference Library
          {hasRefs && (
            <span className="ml-1 rounded-full border border-[#FF5E3A]/40 bg-[#FF5E3A]/10 px-1.5 py-0.5 text-[10px] text-[#FF5E3A]">
              {faceUrls.length + refVideos.length} selected
            </span>
          )}
        </button>
        {showRefs && (
          <div className="mt-3">
            <FaceLibrary onChange={handleFaceSelection} />
          </div>
        )}
      </Panel>

      {/* Output */}
      <Panel className="min-h-[480px]">
        <PanelHeader
          icon={<Atom size={16} className={phase === 'firing' ? 'animate-spin' : 'animate-pulse-glow'} />}
          accent="cyan"
          title="Generated Concepts"
          subtitle="Synthesized from your active intelligence layer"
          accessory={concepts.length > 0 ? <Pill tone="success">{concepts.length} concepts</Pill> : undefined}
        />

        {phase === 'idle' && (
          <div className="grid place-items-center px-6 py-24 text-center">
            <Atom size={40} className="mb-4 text-white/15" />
            <p className="max-w-sm text-sm text-white/40">
              Hit <span className="text-white/70">New Creative Campaign</span> to set your brief,
              audience, and offer — then fire the reactor. The agent walks your frameworks,
              retrieves what has already worked, and drafts grounded concepts.
            </p>
          </div>
        )}

        {phase !== 'idle' && (
          <div className="space-y-4 p-5">
            {/* Live telemetry feed */}
            {(telemetry.length > 0 || phase === 'firing') && (
              <div className="telemetry-console p-3">
                <div className="mb-2 flex items-center gap-2 text-[10px] font-medium uppercase tracking-widest text-white/35">
                  <Radar size={12} className={phase === 'firing' ? 'animate-spin text-glow' : ''} />
                  Reactor Telemetry
                </div>
                <div ref={feedRef} className="max-h-40 space-y-1 overflow-y-auto font-mono text-[11px]">
                  {telemetry.map((t, i) => (
                    <div
                      key={i}
                      className={`flex gap-2 ${
                        t.kind === 'retrieval'
                          ? 'text-cyan/80'
                          : t.kind === 'specialist'
                            ? 'text-warning'
                            : 'text-white/55'
                      }`}
                    >
                      <span className="text-white/25">
                        {t.kind === 'retrieval' ? '└▸' : t.kind === 'specialist' ? '▣' : '›'}
                      </span>
                      <span>{t.text}</span>
                    </div>
                  ))}
                  {phase === 'firing' && (
                    <div className="flex items-center gap-2 text-glow">
                      <Loader2 size={11} className="animate-spin" /> working…
                    </div>
                  )}
                </div>
              </div>
            )}

            {error && (
              <div className="rounded-lg border border-danger/30 bg-danger/[0.06] p-3 text-sm text-danger">
                {error}
              </div>
            )}

            {concepts.map((c, i) => {
              const image = imageFor(c)
              const video = videoFor(c)
              const wantsVideo = isVideoConcept(c)
              const creativeBusy =
                creatives[c.text]?.status === 'working' || video?.status === 'rendering'
              return (
                <div
                  key={i}
                  className={`glass-hover animate-fade-up stagger-${(i % 8) + 1} rounded-xl border border-border bg-surface/40 p-4`}
                >
                  <div className="mb-1.5 flex items-center justify-between gap-2">
                    <div className="flex items-center gap-2">
                      <Pill tone="primary">{c.type}</Pill>
                      {typeof c.score === 'number' && (
                        <Pill tone={c.score >= 8 ? 'success' : 'warning'}>{c.score}/10</Pill>
                      )}
                    </div>
                    <div className="flex items-center gap-3">
                      {c.type.includes('Concept') && (
                        <button
                          type="button"
                          onClick={() => generateCreative(c)}
                          disabled={creativeBusy}
                          className="flex items-center gap-1 text-[11px] text-white/40 hover:text-cyan disabled:opacity-60"
                        >
                          {creativeBusy ? (
                            <Loader2 size={12} className="animate-spin" />
                          ) : wantsVideo ? (
                            <Film size={12} />
                          ) : (
                            <ImageIcon size={12} />
                          )}
                          {wantsVideo ? 'Generate Video Creative' : 'Generate Image Creative'}
                        </button>
                      )}
                      {wantsVideo && hasRefs && (
                        <button
                          type="button"
                          onClick={() => generateUGC(c)}
                          disabled={creativeBusy}
                          className="flex items-center gap-1 text-[11px] text-white/40 hover:text-cyan disabled:opacity-60"
                          title={`Generate with ${faceUrls.length} reference image${faceUrls.length === 1 ? '' : 's'}${refVideos.length ? ` + ${refVideos.length} video${refVideos.length === 1 ? '' : 's'}` : ''} (Seedance 2.0 reference-to-video)`}
                        >
                          <Users size={12} />
                          Generate UGC
                        </button>
                      )}
                      {image && !video && (
                        <button
                          type="button"
                          onClick={() => animate(c, image)}
                          className="flex items-center gap-1 text-[11px] text-white/40 hover:text-cyan"
                        >
                          <Film size={12} />
                          Animate
                        </button>
                      )}
                      <button
                        type="button"
                        onClick={() => markWinner(c)}
                        disabled={logged.has(c.text)}
                        className="flex items-center gap-1 text-[11px] text-white/40 hover:text-success disabled:text-success"
                      >
                        <Trophy size={12} />
                        {logged.has(c.text) ? 'Logged' : 'Mark winner'}
                      </button>
                      <button
                        type="button"
                        onClick={() => copy(c.text)}
                        className="flex items-center gap-1 text-[11px] text-white/40 hover:text-glow"
                      >
                        {copied === c.text ? <Check size={12} /> : <CopyIcon size={12} />}
                        {copied === c.text ? 'Copied' : 'Copy'}
                      </button>
                    </div>
                  </div>
                  <p className="text-sm text-white/80">{c.text}</p>
                  {(c.basis || c.learningCheck) && (
                    <div className="mt-2 space-y-1 border-t border-border pt-2 text-[11px] text-white/40">
                      {c.basis && (
                        <p>
                          <span className="text-glow/70">Grounded in:</span> {c.basis}
                        </p>
                      )}
                      {c.learningCheck && (
                        <p>
                          <span className="text-success/70">Rubric:</span> {c.learningCheck}
                        </p>
                      )}
                    </div>
                  )}

                  {/* Generated still creative (Higgsfield agent or manual) */}
                  {image && (
                    // eslint-disable-next-line @next/next/no-img-element
                    <img src={image} alt={c.type} className="mt-3 w-full rounded-lg border border-border" />
                  )}

                  {/* Higgsfield video */}
                  {video?.status === 'done' && video.url && (
                    <video
                      src={video.url}
                      controls
                      playsInline
                      className="mt-3 w-full rounded-lg border border-border"
                    />
                  )}
                  {video?.status === 'rendering' && (
                    <div className="mt-3 grid aspect-video w-full place-items-center rounded-lg border border-border bg-background/40">
                      <span className="flex items-center gap-2 text-xs text-cyan">
                        <Loader2 size={14} className="animate-spin" /> Rendering video…
                      </span>
                    </div>
                  )}
                  {video?.status === 'error' && (
                    <p className="mt-3 rounded-lg border border-warning/30 bg-warning/[0.06] p-2 text-[11px] text-warning">
                      {video.message || 'Video render failed — check FAL_KEY / HF_CREDENTIALS or try again.'}
                    </p>
                  )}

                  {/* Creative render status (in-flight / error) */}
                  {creatives[c.text]?.status === 'working' && (
                    <div className="mt-3 grid aspect-square w-full place-items-center rounded-lg border border-border bg-background/40">
                      <span className="flex items-center gap-2 text-xs text-cyan">
                        <Loader2 size={14} className="animate-spin" /> Rendering creative…
                      </span>
                    </div>
                  )}
                  {creatives[c.text]?.status === 'error' && (
                    <p className="mt-3 rounded-lg border border-warning/30 bg-warning/[0.06] p-2 text-[11px] text-warning">
                      {creatives[c.text].message}
                    </p>
                  )}
                </div>
              )
            })}
          </div>
        )}
      </Panel>

      <ReactorModal open={modalOpen} onClose={() => setModalOpen(false)} onFire={fire} />
    </div>
  )
}
