'use client'

import { createContext, useCallback, useContext, useRef, useState, type ReactNode } from 'react'
import { briefToPrompt, type ProductionBrief } from '@/lib/reactor-inputs'
import type { Verdict, OutcomeAttributes } from '@/lib/outcomes'

/* -------------------------------------------------------------------------- */
/*  Shared run types                                                          */
/* -------------------------------------------------------------------------- */

export interface Concept {
  type: string
  text: string
  basis?: string
  learningCheck?: string
  score?: number
  imageUrl?: string
  productionBrief?: ProductionBrief
}

export interface TelemetryLine {
  text: string
  kind: 'step' | 'retrieval' | 'intelligence'
  /** Intelligence layer header, e.g. "Market Intelligence". */
  label?: string
  /** Builder-facing confidence band, e.g. "High". */
  confidence?: string
}

export type VideoUiState = { status: 'rendering' | 'done' | 'error'; url?: string; message?: string }

export type CreativeState = { status: 'working' | 'done' | 'error'; url?: string; message?: string }

type RunPhase = 'idle' | 'firing' | 'done'

// Options threaded in from the Workbench form (model picks + reference library)
// at call time, so the provider never needs to hold transient form state.
interface CreativeOpts {
  imageModel?: string
  videoModel?: string
}
interface VideoOpts {
  videoModel?: string
}
interface UgcOpts {
  videoModel?: string
  faceUrls: string[]
  refVideos: string[]
}

// Normalize an output/concept type so agent-generated media keyed by type lines
// up with the concept the agent submits ("Static Concepts" ≈ "Static Concept").
export const normType = (s: string) => s.toLowerCase().replace(/s$/, '').trim()

const isVideoConcept = (c: Concept) => /video|testimonial/i.test(c.type)

/* -------------------------------------------------------------------------- */
/*  Context shape                                                             */
/* -------------------------------------------------------------------------- */

interface ReactorRunValue {
  phase: RunPhase
  concepts: Concept[]
  telemetry: TelemetryLine[]
  error: string | null
  logged: Set<string>
  streamReactor: (payload: Record<string, unknown>) => Promise<void>
  generateCreative: (c: Concept, opts: CreativeOpts) => Promise<void>
  animate: (c: Concept, imageUrl: string, opts: VideoOpts) => Promise<void>
  generateUGC: (c: Concept, opts: UgcOpts) => Promise<void>
  markOutcome: (c: Concept, verdict: Verdict, angle: string, attributes: OutcomeAttributes) => Promise<void>
  imageFor: (c: Concept) => string | undefined
  videoFor: (c: Concept) => VideoUiState | undefined
  creativeStateFor: (c: Concept) => CreativeState | undefined
}

const ReactorRunContext = createContext<ReactorRunValue | null>(null)

/* -------------------------------------------------------------------------- */
/*  Provider — mounted in the persistent platform layout so an in-flight run  */
/*  survives navigation between dashboards (the stream + polls keep writing    */
/*  into this state instead of a page component that unmounts).                */
/* -------------------------------------------------------------------------- */

export function ReactorRunProvider({ children }: { children: ReactNode }) {
  const [phase, setPhase] = useState<RunPhase>('idle')
  const [concepts, setConcepts] = useState<Concept[]>([])
  const [telemetry, setTelemetry] = useState<TelemetryLine[]>([])
  const [error, setError] = useState<string | null>(null)
  const [logged, setLogged] = useState<Set<string>>(new Set())
  const [creatives, setCreatives] = useState<Record<string, CreativeState>>({})
  // Higgsfield media generated by the agent during the run, keyed by concept type.
  const [agentMedia, setAgentMedia] = useState<
    Record<string, { image?: string; video?: VideoUiState }>
  >({})
  // Manually triggered renders, keyed by concept text.
  const [manualVideos, setManualVideos] = useState<Record<string, VideoUiState>>({})

  const pushTelemetry = useCallback((line: TelemetryLine) => {
    setTelemetry((prev) => [...prev, line])
  }, [])

  // Poll a video render until it completes or fails (model-aware across providers).
  const pollVideo = useCallback(
    async (
      requestId: string,
      model: string | undefined,
      onUpdate: (s: VideoUiState) => void,
      responseUrl?: string,
    ) => {
      const modelQuery = model ? `&model=${encodeURIComponent(model)}` : ''
      const responseQuery = responseUrl ? `&responseUrl=${encodeURIComponent(responseUrl)}` : ''
      for (let i = 0; i < 90; i++) {
        await new Promise((r) => setTimeout(r, 4000))
        try {
          const res = await fetch(
            `/api/generate-video?requestId=${encodeURIComponent(requestId)}${modelQuery}${responseQuery}`,
          ).then((r) => r.json())
          if (res.status === 'completed' && res.videoUrl) {
            onUpdate({ status: 'done', url: res.videoUrl })
            return
          }
          if (res.status === 'failed' || res.status === 'nsfw') {
            onUpdate({ status: 'error' })
            return
          }
        } catch {
          /* transient — keep polling */
        }
      }
      onUpdate({ status: 'error' })
    },
    [],
  )

  // Shared streaming runner — both the classic panel and the guided modal post
  // into the same SSE pipeline; only the request payload differs.
  const streamReactor = useCallback(
    async (payload: Record<string, unknown>) => {
      setPhase('firing')
      setConcepts([])
      setTelemetry([])
      setError(null)
      setAgentMedia({})
      setManualVideos({})
      setCreatives({})
      setLogged(new Set())

      try {
        const res = await fetch('/api/campaign-reactor', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(payload),
        })
        if (!res.body) throw new Error('No response stream')

        const reader = res.body.getReader()
        const decoder = new TextDecoder()
        let buffer = ''

        // Parse the SSE stream line by line.
        for (;;) {
          const { done, value } = await reader.read()
          if (done) break
          buffer += decoder.decode(value, { stream: true })
          const parts = buffer.split('\n\n')
          buffer = parts.pop() ?? ''
          for (const part of parts) {
            const line = part.replace(/^data: /, '').trim()
            if (!line) continue
            let ev: { type: string; [k: string]: unknown }
            try {
              ev = JSON.parse(line)
            } catch {
              continue
            }
            if (ev.type === 'step') pushTelemetry({ text: ev.text as string, kind: 'step' })
            else if (ev.type === 'retrieval')
              pushTelemetry({ text: `${ev.system} · ${ev.title}`, kind: 'retrieval' })
            else if (ev.type === 'delegate')
              pushTelemetry({
                text:
                  ev.status === 'start'
                    ? 'Analyzing…'
                    : ((ev.summary as string) || 'Findings ready'),
                kind: 'intelligence',
                label: (ev.label as string) || (ev.agent as string) || 'Intelligence',
                confidence: ev.confidence as string | undefined,
              })
            else if (ev.type === 'media') {
              const key = normType((ev.conceptType as string) || '')
              if (ev.mediaType === 'image') {
                setAgentMedia((p) => ({ ...p, [key]: { ...p[key], image: ev.url as string } }))
              } else if (ev.mediaType === 'video') {
                setAgentMedia((p) => ({ ...p, [key]: { ...p[key], video: { status: 'rendering' } } }))
                const requestId = ev.requestId as string | undefined
                if (requestId) {
                  pollVideo(
                    requestId,
                    ev.model as string | undefined,
                    (s) => setAgentMedia((p) => ({ ...p, [key]: { ...p[key], video: s } })),
                    ev.responseUrl as string | undefined,
                  )
                }
              }
            } else if (ev.type === 'concept') setConcepts((p) => [...p, ev.concept as Concept])
            else if (ev.type === 'error') setError(ev.message as string)
            else if (ev.type === 'done') setPhase('done')
          }
        }
        setPhase('done')
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Reactor failed')
        setPhase('done')
      }
    },
    [pushTelemetry, pollVideo],
  )

  // Render a video ad straight from the concept's brief (text-to-video).
  const generateVideoCreative = useCallback(
    async (c: Concept, videoModel?: string) => {
      setManualVideos((p) => ({ ...p, [c.text]: { status: 'rendering' } }))
      try {
        const res = await fetch('/api/generate-video', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            prompt: c.productionBrief ? briefToPrompt(c.productionBrief, c.text) : c.text,
            mode: 'text-to-video',
            model: videoModel,
            aspectRatio: '9:16',
          }),
        }).then((r) => r.json())

        if (res.success && res.requestId) {
          pollVideo(
            res.requestId,
            res.modelId,
            (s) => setManualVideos((p) => ({ ...p, [c.text]: s })),
            res.responseUrl,
          )
        } else {
          setManualVideos((p) => ({
            ...p,
            [c.text]: {
              status: 'error',
              message:
                res.error ||
                (res.demo ? 'No video API key set — add FAL_KEY or HF_CREDENTIALS' : 'Video render failed'),
            },
          }))
        }
      } catch {
        setManualVideos((p) => ({ ...p, [c.text]: { status: 'error', message: 'Video render failed' } }))
      }
    },
    [pollVideo],
  )

  // Turn a concept's design brief into the right creative — image or video.
  const generateCreative = useCallback(
    async (c: Concept, opts: CreativeOpts) => {
      if (isVideoConcept(c)) return generateVideoCreative(c, opts.videoModel)

      setCreatives((p) => ({ ...p, [c.text]: { status: 'working' } }))
      try {
        const res = await fetch('/api/generate-image', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            prompt: briefToPrompt(
              c.productionBrief,
              `${c.text}\n\nRender as a premium Meta ad creative for The Professional Builder — photographic, on-site builder context, high contrast, leave room for text overlay.`,
            ),
            aspectRatio: '1:1',
            model: opts.imageModel,
          }),
        }).then((r) => r.json())

        if (res.success && res.imageUrl) {
          setCreatives((p) => ({ ...p, [c.text]: { status: 'done', url: res.imageUrl } }))
        } else {
          setCreatives((p) => ({
            ...p,
            [c.text]: {
              status: 'error',
              message:
                res.error ||
                (res.demo
                  ? 'No image API key set — add FAL_KEY, GEMINI_API_KEY, OPENAI_API_KEY, or HF_CREDENTIALS'
                  : 'Generation failed'),
            },
          }))
        }
      } catch {
        setCreatives((p) => ({ ...p, [c.text]: { status: 'error', message: 'Generation failed' } }))
      }
    },
    [generateVideoCreative],
  )

  // Animate an existing still into a video (image -> video).
  const animate = useCallback(
    async (c: Concept, imageUrl: string, opts: VideoOpts) => {
      setManualVideos((p) => ({ ...p, [c.text]: { status: 'rendering' } }))
      try {
        const res = await fetch('/api/generate-video', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            imageUrl,
            mode: 'image-to-video',
            model: opts.videoModel,
            prompt: `Cinematic motion for a builder ad: ${c.text}`,
          }),
        }).then((r) => r.json())

        if (res.success && res.requestId) {
          pollVideo(
            res.requestId,
            res.modelId,
            (s) => setManualVideos((p) => ({ ...p, [c.text]: s })),
            res.responseUrl,
          )
        } else {
          setManualVideos((p) => ({
            ...p,
            [c.text]: {
              status: 'error',
              message:
                res.error ||
                (res.demo ? 'No video API key set — add FAL_KEY or HF_CREDENTIALS' : 'Video render failed'),
            },
          }))
        }
      } catch {
        setManualVideos((p) => ({ ...p, [c.text]: { status: 'error', message: 'Video render failed' } }))
      }
    },
    [pollVideo],
  )

  // Generate UGC with a consistent face — Seedance 2.0 reference-to-video.
  const generateUGC = useCallback(
    async (c: Concept, opts: UgcOpts) => {
      if (opts.faceUrls.length === 0 && opts.refVideos.length === 0) return
      setManualVideos((p) => ({ ...p, [c.text]: { status: 'rendering' } }))
      try {
        const res = await fetch('/api/generate-video', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            prompt: c.text,
            mode: 'reference-to-video',
            model: 'seedance-2.0',
            imageUrls: opts.faceUrls,
            videoUrls: opts.refVideos,
            aspectRatio: '9:16',
          }),
        }).then((r) => r.json())

        if (res.success && res.requestId) {
          pollVideo(
            res.requestId,
            res.modelId,
            (s) => setManualVideos((p) => ({ ...p, [c.text]: s })),
            res.responseUrl,
          )
        } else {
          setManualVideos((p) => ({
            ...p,
            [c.text]: {
              status: 'error',
              message: res.error || (res.demo ? 'No video API key set — add FAL_KEY' : 'UGC render failed'),
            },
          }))
        }
      } catch {
        setManualVideos((p) => ({ ...p, [c.text]: { status: 'error', message: 'UGC render failed' } }))
      }
    },
    [pollVideo],
  )

  // Log an outcome — wins feed back into the knowledge layer as new patterns.
  const markOutcome = useCallback(
    async (c: Concept, verdict: Verdict, angle: string, attributes: OutcomeAttributes) => {
      setLogged((prev) => new Set(prev).add(c.text))
      try {
        await fetch('/api/campaign-reactor/outcome', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ angle, concept: c, verdict, attributes }),
        })
      } catch {
        /* best-effort logging */
      }
    },
    [],
  )

  const imageFor = useCallback(
    (c: Concept) => c.imageUrl || agentMedia[normType(c.type)]?.image || creatives[c.text]?.url,
    [agentMedia, creatives],
  )
  const videoFor = useCallback(
    (c: Concept): VideoUiState | undefined => manualVideos[c.text] || agentMedia[normType(c.type)]?.video,
    [manualVideos, agentMedia],
  )
  const creativeStateFor = useCallback((c: Concept) => creatives[c.text], [creatives])

  const value: ReactorRunValue = {
    phase,
    concepts,
    telemetry,
    error,
    logged,
    streamReactor,
    generateCreative,
    animate,
    generateUGC,
    markOutcome,
    imageFor,
    videoFor,
    creativeStateFor,
  }

  return <ReactorRunContext.Provider value={value}>{children}</ReactorRunContext.Provider>
}

export function useReactorRun() {
  const ctx = useContext(ReactorRunContext)
  if (!ctx) throw new Error('useReactorRun must be used within a ReactorRunProvider')
  return ctx
}
